# Generated by Django 3.2.7 on 2021-10-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0003_rename_details_carinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='/car.jpg', null=True, upload_to='carlisting\\static\\images', verbose_name='car image'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='owner name')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='registration date')),
                ('county_of_residence', models.CharField(max_length=50, verbose_name='county of residence')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carlisting.car', verbose_name='')),
            ],
        ),
    ]
